# SPDX-FileCopyrightText: 2024 ETH Zurich and University of Bologna
# SPDX-License-Identifier: Apache-2.0
#
# Build-time script: generates a prefixed symbol assembly file and a matching
# C header from a device ELF, using llvm-nm to extract the symbol table.
#
# Required variables (pass via cmake -D):
#   NM          - Path to llvm-nm
#   TARGET_NAME - Device target name (used as symbol prefix)
#   ELF         - Path to device ELF
#   OUT_ASM     - Output assembler file (.s)
#   OUT_H       - Output header file (.h)

execute_process(
    COMMAND ${NM} --defined-only --extern-only -n ${ELF}
    OUTPUT_VARIABLE NM_OUTPUT
    RESULT_VARIABLE NM_RESULT
    ERROR_QUIET
)

if(NOT NM_RESULT EQUAL 0)
    message(FATAL_ERROR "[CHIMERA] nm failed on ${ELF}")
endif()

string(REPLACE "\n" ";" NM_LINES "${NM_OUTPUT}")

set(ASM_SYMS "")
set(H_DECLS  "")
set(BINARY_START_WRITTEN FALSE)

foreach(line IN LISTS NM_LINES)
    if(NOT line)
        continue()
    endif()

    # nm output format: <address> <type> <name>
    if(NOT line MATCHES "^([0-9a-fA-F]+)[ \t]+([TtDdBbRr])[ \t]+(.+)$")
        continue()
    endif()

    set(ADDR "${CMAKE_MATCH_1}")
    set(TYPE "${CMAKE_MATCH_2}")
    set(SYM  "${CMAKE_MATCH_3}")
    string(STRIP "${SYM}" SYM)

    # Skip linker-generated private symbols
    if(SYM MATCHES "^__")
        continue()
    endif()

    # First text symbol defines the load address of the binary
    if(NOT BINARY_START_WRITTEN AND TYPE MATCHES "[Tt]")
        string(APPEND ASM_SYMS ".global ${TARGET_NAME}_binary_start\n")
        string(APPEND ASM_SYMS ".set    ${TARGET_NAME}_binary_start, 0x${ADDR}\n\n")
        string(APPEND H_DECLS  "/* Start of device binary in device address space */\n")
        string(APPEND H_DECLS  "extern char ${TARGET_NAME}_binary_start[];\n\n")
        set(BINARY_START_WRITTEN TRUE)
    endif()

    set(PSYM "${TARGET_NAME}_${SYM}")
    string(APPEND ASM_SYMS ".global ${PSYM}\n")
    string(APPEND ASM_SYMS ".set    ${PSYM}, 0x${ADDR}\n")
    string(APPEND H_DECLS  "extern char ${PSYM}[]; /* 0x${ADDR} */\n")
endforeach()

# Write assembly file
file(WRITE "${OUT_ASM}"
    "/* Auto-generated device symbols for ${TARGET_NAME} - do not edit */\n\n"
    "${ASM_SYMS}"
)

# Write header file
string(TOUPPER "${TARGET_NAME}" GUARD)
file(WRITE "${OUT_H}"
    "/* Auto-generated header for ${TARGET_NAME} device symbols */\n"
    "/* Generated by cmake/GenerateDeviceSymbols.cmake - do not edit */\n"
    "\n"
    "#ifndef ${GUARD}_SYMBOLS_H\n"
    "#define ${GUARD}_SYMBOLS_H\n"
    "\n"
    "#ifdef __cplusplus\n"
    "extern \"C\" {\n"
    "#endif\n"
    "\n"
    "${H_DECLS}"
    "\n"
    "#ifdef __cplusplus\n"
    "}\n"
    "#endif\n"
    "\n"
    "#endif /* ${GUARD}_SYMBOLS_H */\n"
)

message(STATUS "[CHIMERA] Generated device symbols for ${TARGET_NAME}")
